// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: protos/chattingProtocol.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from protos/chattingProtocol.proto</summary>
public static partial class ChattingProtocolReflection {

  #region Descriptor
  /// <summary>File descriptor for protos/chattingProtocol.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ChattingProtocolReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Ch1wcm90b3MvY2hhdHRpbmdQcm90b2NvbC5wcm90byIuCh1DMlNDaGF0dGlu",
          "Z1NlcnZlckxvZ2luUmVxdWVzdBINCgVlbWFpbBgBIAEoCSIkCiJDMlNDaGF0",
          "dGluZ1NlcnZlckNyZWF0ZVJvb21SZXF1ZXN0IkkKIEMyU0NoYXR0aW5nU2Vy",
          "dmVySm9pblJvb21SZXF1ZXN0EhYKDmNoYXR0aW5nUm9vbUlkGAEgASgFEg0K",
          "BWVtYWlsGAIgASgJIkIKHlMyQ0NoYXR0aW5nU2VydmVyTG9naW5SZXNwb25z",
          "ZRIPCgdzdWNjZXNzGAEgASgIEg8KB21lc3NhZ2UYAiABKAkiPQojUzJDQ2hh",
          "dHRpbmdTZXJ2ZXJDcmVhdGVSb29tUmVzcG9uc2USFgoOY2hhdHRpbmdSb29t",
          "SWQYASABKAUinwMKDkNoYXR0aW5nUGFja2V0EkQKGmNoYXR0aW5nU2VydmVy",
          "TG9naW5SZXF1ZXN0GAEgASgLMh4uQzJTQ2hhdHRpbmdTZXJ2ZXJMb2dpblJl",
          "cXVlc3RIABJGChtjaGF0dGluZ1NlcnZlckxvZ2luUmVzcG9uc2UYAiABKAsy",
          "Hy5TMkNDaGF0dGluZ1NlcnZlckxvZ2luUmVzcG9uc2VIABJOCh9jaGF0dGlu",
          "Z1NlcnZlckNyZWF0ZVJvb21SZXF1ZXN0GAMgASgLMiMuQzJTQ2hhdHRpbmdT",
          "ZXJ2ZXJDcmVhdGVSb29tUmVxdWVzdEgAElAKIGNoYXR0aW5nU2VydmVyQ3Jl",
          "YXRlUm9vbVJlc3BvbnNlGAQgASgLMiQuUzJDQ2hhdHRpbmdTZXJ2ZXJDcmVh",
          "dGVSb29tUmVzcG9uc2VIABJKCh1jaGF0dGluZ1NlcnZlckpvaW5Sb29tUmVx",
          "dWVzdBgFIAEoCzIhLkMyU0NoYXR0aW5nU2VydmVySm9pblJvb21SZXF1ZXN0",
          "SABCEQoPY2hhdHRpbmdQYXlsb2FkYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::C2SChattingServerLoginRequest), global::C2SChattingServerLoginRequest.Parser, new[]{ "Email" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::C2SChattingServerCreateRoomRequest), global::C2SChattingServerCreateRoomRequest.Parser, null, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::C2SChattingServerJoinRoomRequest), global::C2SChattingServerJoinRoomRequest.Parser, new[]{ "ChattingRoomId", "Email" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::S2CChattingServerLoginResponse), global::S2CChattingServerLoginResponse.Parser, new[]{ "Success", "Message" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::S2CChattingServerCreateRoomResponse), global::S2CChattingServerCreateRoomResponse.Parser, new[]{ "ChattingRoomId" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ChattingPacket), global::ChattingPacket.Parser, new[]{ "ChattingServerLoginRequest", "ChattingServerLoginResponse", "ChattingServerCreateRoomRequest", "ChattingServerCreateRoomResponse", "ChattingServerJoinRoomRequest" }, new[]{ "ChattingPayload" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
/// <summary>
///------------------------------------
/// 로그인 요청
/// email : 로그인 대상 email
///------------------------------------
/// </summary>
public sealed partial class C2SChattingServerLoginRequest : pb::IMessage<C2SChattingServerLoginRequest> {
  private static readonly pb::MessageParser<C2SChattingServerLoginRequest> _parser = new pb::MessageParser<C2SChattingServerLoginRequest>(() => new C2SChattingServerLoginRequest());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<C2SChattingServerLoginRequest> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ChattingProtocolReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public C2SChattingServerLoginRequest() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public C2SChattingServerLoginRequest(C2SChattingServerLoginRequest other) : this() {
    email_ = other.email_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public C2SChattingServerLoginRequest Clone() {
    return new C2SChattingServerLoginRequest(this);
  }

  /// <summary>Field number for the "email" field.</summary>
  public const int EmailFieldNumber = 1;
  private string email_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Email {
    get { return email_; }
    set {
      email_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as C2SChattingServerLoginRequest);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(C2SChattingServerLoginRequest other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Email != other.Email) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Email.Length != 0) hash ^= Email.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Email.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Email);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Email.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Email);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(C2SChattingServerLoginRequest other) {
    if (other == null) {
      return;
    }
    if (other.Email.Length != 0) {
      Email = other.Email;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Email = input.ReadString();
          break;
        }
      }
    }
  }

}

/// <summary>
///------------------------------------
/// 방 생성
///------------------------------------
/// </summary>
public sealed partial class C2SChattingServerCreateRoomRequest : pb::IMessage<C2SChattingServerCreateRoomRequest> {
  private static readonly pb::MessageParser<C2SChattingServerCreateRoomRequest> _parser = new pb::MessageParser<C2SChattingServerCreateRoomRequest>(() => new C2SChattingServerCreateRoomRequest());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<C2SChattingServerCreateRoomRequest> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ChattingProtocolReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public C2SChattingServerCreateRoomRequest() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public C2SChattingServerCreateRoomRequest(C2SChattingServerCreateRoomRequest other) : this() {
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public C2SChattingServerCreateRoomRequest Clone() {
    return new C2SChattingServerCreateRoomRequest(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as C2SChattingServerCreateRoomRequest);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(C2SChattingServerCreateRoomRequest other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(C2SChattingServerCreateRoomRequest other) {
    if (other == null) {
      return;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
      }
    }
  }

}

/// <summary>
///------------------------------------
/// 방 생성
/// roomId : 참가할 방 아이디
/// email : 참가하는 유저 email
///------------------------------------
/// </summary>
public sealed partial class C2SChattingServerJoinRoomRequest : pb::IMessage<C2SChattingServerJoinRoomRequest> {
  private static readonly pb::MessageParser<C2SChattingServerJoinRoomRequest> _parser = new pb::MessageParser<C2SChattingServerJoinRoomRequest>(() => new C2SChattingServerJoinRoomRequest());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<C2SChattingServerJoinRoomRequest> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ChattingProtocolReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public C2SChattingServerJoinRoomRequest() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public C2SChattingServerJoinRoomRequest(C2SChattingServerJoinRoomRequest other) : this() {
    chattingRoomId_ = other.chattingRoomId_;
    email_ = other.email_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public C2SChattingServerJoinRoomRequest Clone() {
    return new C2SChattingServerJoinRoomRequest(this);
  }

  /// <summary>Field number for the "chattingRoomId" field.</summary>
  public const int ChattingRoomIdFieldNumber = 1;
  private int chattingRoomId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int ChattingRoomId {
    get { return chattingRoomId_; }
    set {
      chattingRoomId_ = value;
    }
  }

  /// <summary>Field number for the "email" field.</summary>
  public const int EmailFieldNumber = 2;
  private string email_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Email {
    get { return email_; }
    set {
      email_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as C2SChattingServerJoinRoomRequest);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(C2SChattingServerJoinRoomRequest other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (ChattingRoomId != other.ChattingRoomId) return false;
    if (Email != other.Email) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (ChattingRoomId != 0) hash ^= ChattingRoomId.GetHashCode();
    if (Email.Length != 0) hash ^= Email.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (ChattingRoomId != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(ChattingRoomId);
    }
    if (Email.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Email);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (ChattingRoomId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(ChattingRoomId);
    }
    if (Email.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Email);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(C2SChattingServerJoinRoomRequest other) {
    if (other == null) {
      return;
    }
    if (other.ChattingRoomId != 0) {
      ChattingRoomId = other.ChattingRoomId;
    }
    if (other.Email.Length != 0) {
      Email = other.Email;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          ChattingRoomId = input.ReadInt32();
          break;
        }
        case 18: {
          Email = input.ReadString();
          break;
        }
      }
    }
  }

}

/// <summary>
///------------------------------------
/// 로그인 응답
/// success : 로그인 성공 여부
/// message : 성공 여부에 따른 메세지
///------------------------------------
/// </summary>
public sealed partial class S2CChattingServerLoginResponse : pb::IMessage<S2CChattingServerLoginResponse> {
  private static readonly pb::MessageParser<S2CChattingServerLoginResponse> _parser = new pb::MessageParser<S2CChattingServerLoginResponse>(() => new S2CChattingServerLoginResponse());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<S2CChattingServerLoginResponse> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ChattingProtocolReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public S2CChattingServerLoginResponse() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public S2CChattingServerLoginResponse(S2CChattingServerLoginResponse other) : this() {
    success_ = other.success_;
    message_ = other.message_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public S2CChattingServerLoginResponse Clone() {
    return new S2CChattingServerLoginResponse(this);
  }

  /// <summary>Field number for the "success" field.</summary>
  public const int SuccessFieldNumber = 1;
  private bool success_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Success {
    get { return success_; }
    set {
      success_ = value;
    }
  }

  /// <summary>Field number for the "message" field.</summary>
  public const int MessageFieldNumber = 2;
  private string message_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Message {
    get { return message_; }
    set {
      message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as S2CChattingServerLoginResponse);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(S2CChattingServerLoginResponse other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Success != other.Success) return false;
    if (Message != other.Message) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Success != false) hash ^= Success.GetHashCode();
    if (Message.Length != 0) hash ^= Message.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Success != false) {
      output.WriteRawTag(8);
      output.WriteBool(Success);
    }
    if (Message.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Message);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Success != false) {
      size += 1 + 1;
    }
    if (Message.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(S2CChattingServerLoginResponse other) {
    if (other == null) {
      return;
    }
    if (other.Success != false) {
      Success = other.Success;
    }
    if (other.Message.Length != 0) {
      Message = other.Message;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Success = input.ReadBool();
          break;
        }
        case 18: {
          Message = input.ReadString();
          break;
        }
      }
    }
  }

}

/// <summary>
///-----------------------------------------
/// 방 생성 응답
/// roomId : 방 번호
///-----------------------------------------
/// </summary>
public sealed partial class S2CChattingServerCreateRoomResponse : pb::IMessage<S2CChattingServerCreateRoomResponse> {
  private static readonly pb::MessageParser<S2CChattingServerCreateRoomResponse> _parser = new pb::MessageParser<S2CChattingServerCreateRoomResponse>(() => new S2CChattingServerCreateRoomResponse());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<S2CChattingServerCreateRoomResponse> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ChattingProtocolReflection.Descriptor.MessageTypes[4]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public S2CChattingServerCreateRoomResponse() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public S2CChattingServerCreateRoomResponse(S2CChattingServerCreateRoomResponse other) : this() {
    chattingRoomId_ = other.chattingRoomId_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public S2CChattingServerCreateRoomResponse Clone() {
    return new S2CChattingServerCreateRoomResponse(this);
  }

  /// <summary>Field number for the "chattingRoomId" field.</summary>
  public const int ChattingRoomIdFieldNumber = 1;
  private int chattingRoomId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int ChattingRoomId {
    get { return chattingRoomId_; }
    set {
      chattingRoomId_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as S2CChattingServerCreateRoomResponse);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(S2CChattingServerCreateRoomResponse other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (ChattingRoomId != other.ChattingRoomId) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (ChattingRoomId != 0) hash ^= ChattingRoomId.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (ChattingRoomId != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(ChattingRoomId);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (ChattingRoomId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(ChattingRoomId);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(S2CChattingServerCreateRoomResponse other) {
    if (other == null) {
      return;
    }
    if (other.ChattingRoomId != 0) {
      ChattingRoomId = other.ChattingRoomId;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          ChattingRoomId = input.ReadInt32();
          break;
        }
      }
    }
  }

}

public sealed partial class ChattingPacket : pb::IMessage<ChattingPacket> {
  private static readonly pb::MessageParser<ChattingPacket> _parser = new pb::MessageParser<ChattingPacket>(() => new ChattingPacket());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<ChattingPacket> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ChattingProtocolReflection.Descriptor.MessageTypes[5]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ChattingPacket() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ChattingPacket(ChattingPacket other) : this() {
    switch (other.ChattingPayloadCase) {
      case ChattingPayloadOneofCase.ChattingServerLoginRequest:
        ChattingServerLoginRequest = other.ChattingServerLoginRequest.Clone();
        break;
      case ChattingPayloadOneofCase.ChattingServerLoginResponse:
        ChattingServerLoginResponse = other.ChattingServerLoginResponse.Clone();
        break;
      case ChattingPayloadOneofCase.ChattingServerCreateRoomRequest:
        ChattingServerCreateRoomRequest = other.ChattingServerCreateRoomRequest.Clone();
        break;
      case ChattingPayloadOneofCase.ChattingServerCreateRoomResponse:
        ChattingServerCreateRoomResponse = other.ChattingServerCreateRoomResponse.Clone();
        break;
      case ChattingPayloadOneofCase.ChattingServerJoinRoomRequest:
        ChattingServerJoinRoomRequest = other.ChattingServerJoinRoomRequest.Clone();
        break;
    }

    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ChattingPacket Clone() {
    return new ChattingPacket(this);
  }

  /// <summary>Field number for the "chattingServerLoginRequest" field.</summary>
  public const int ChattingServerLoginRequestFieldNumber = 1;
  /// <summary>
  /// 로그인
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::C2SChattingServerLoginRequest ChattingServerLoginRequest {
    get { return chattingPayloadCase_ == ChattingPayloadOneofCase.ChattingServerLoginRequest ? (global::C2SChattingServerLoginRequest) chattingPayload_ : null; }
    set {
      chattingPayload_ = value;
      chattingPayloadCase_ = value == null ? ChattingPayloadOneofCase.None : ChattingPayloadOneofCase.ChattingServerLoginRequest;
    }
  }

  /// <summary>Field number for the "chattingServerLoginResponse" field.</summary>
  public const int ChattingServerLoginResponseFieldNumber = 2;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::S2CChattingServerLoginResponse ChattingServerLoginResponse {
    get { return chattingPayloadCase_ == ChattingPayloadOneofCase.ChattingServerLoginResponse ? (global::S2CChattingServerLoginResponse) chattingPayload_ : null; }
    set {
      chattingPayload_ = value;
      chattingPayloadCase_ = value == null ? ChattingPayloadOneofCase.None : ChattingPayloadOneofCase.ChattingServerLoginResponse;
    }
  }

  /// <summary>Field number for the "chattingServerCreateRoomRequest" field.</summary>
  public const int ChattingServerCreateRoomRequestFieldNumber = 3;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::C2SChattingServerCreateRoomRequest ChattingServerCreateRoomRequest {
    get { return chattingPayloadCase_ == ChattingPayloadOneofCase.ChattingServerCreateRoomRequest ? (global::C2SChattingServerCreateRoomRequest) chattingPayload_ : null; }
    set {
      chattingPayload_ = value;
      chattingPayloadCase_ = value == null ? ChattingPayloadOneofCase.None : ChattingPayloadOneofCase.ChattingServerCreateRoomRequest;
    }
  }

  /// <summary>Field number for the "chattingServerCreateRoomResponse" field.</summary>
  public const int ChattingServerCreateRoomResponseFieldNumber = 4;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::S2CChattingServerCreateRoomResponse ChattingServerCreateRoomResponse {
    get { return chattingPayloadCase_ == ChattingPayloadOneofCase.ChattingServerCreateRoomResponse ? (global::S2CChattingServerCreateRoomResponse) chattingPayload_ : null; }
    set {
      chattingPayload_ = value;
      chattingPayloadCase_ = value == null ? ChattingPayloadOneofCase.None : ChattingPayloadOneofCase.ChattingServerCreateRoomResponse;
    }
  }

  /// <summary>Field number for the "chattingServerJoinRoomRequest" field.</summary>
  public const int ChattingServerJoinRoomRequestFieldNumber = 5;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::C2SChattingServerJoinRoomRequest ChattingServerJoinRoomRequest {
    get { return chattingPayloadCase_ == ChattingPayloadOneofCase.ChattingServerJoinRoomRequest ? (global::C2SChattingServerJoinRoomRequest) chattingPayload_ : null; }
    set {
      chattingPayload_ = value;
      chattingPayloadCase_ = value == null ? ChattingPayloadOneofCase.None : ChattingPayloadOneofCase.ChattingServerJoinRoomRequest;
    }
  }

  private object chattingPayload_;
  /// <summary>Enum of possible cases for the "chattingPayload" oneof.</summary>
  public enum ChattingPayloadOneofCase {
    None = 0,
    ChattingServerLoginRequest = 1,
    ChattingServerLoginResponse = 2,
    ChattingServerCreateRoomRequest = 3,
    ChattingServerCreateRoomResponse = 4,
    ChattingServerJoinRoomRequest = 5,
  }
  private ChattingPayloadOneofCase chattingPayloadCase_ = ChattingPayloadOneofCase.None;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ChattingPayloadOneofCase ChattingPayloadCase {
    get { return chattingPayloadCase_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearChattingPayload() {
    chattingPayloadCase_ = ChattingPayloadOneofCase.None;
    chattingPayload_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as ChattingPacket);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(ChattingPacket other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(ChattingServerLoginRequest, other.ChattingServerLoginRequest)) return false;
    if (!object.Equals(ChattingServerLoginResponse, other.ChattingServerLoginResponse)) return false;
    if (!object.Equals(ChattingServerCreateRoomRequest, other.ChattingServerCreateRoomRequest)) return false;
    if (!object.Equals(ChattingServerCreateRoomResponse, other.ChattingServerCreateRoomResponse)) return false;
    if (!object.Equals(ChattingServerJoinRoomRequest, other.ChattingServerJoinRoomRequest)) return false;
    if (ChattingPayloadCase != other.ChattingPayloadCase) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (chattingPayloadCase_ == ChattingPayloadOneofCase.ChattingServerLoginRequest) hash ^= ChattingServerLoginRequest.GetHashCode();
    if (chattingPayloadCase_ == ChattingPayloadOneofCase.ChattingServerLoginResponse) hash ^= ChattingServerLoginResponse.GetHashCode();
    if (chattingPayloadCase_ == ChattingPayloadOneofCase.ChattingServerCreateRoomRequest) hash ^= ChattingServerCreateRoomRequest.GetHashCode();
    if (chattingPayloadCase_ == ChattingPayloadOneofCase.ChattingServerCreateRoomResponse) hash ^= ChattingServerCreateRoomResponse.GetHashCode();
    if (chattingPayloadCase_ == ChattingPayloadOneofCase.ChattingServerJoinRoomRequest) hash ^= ChattingServerJoinRoomRequest.GetHashCode();
    hash ^= (int) chattingPayloadCase_;
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (chattingPayloadCase_ == ChattingPayloadOneofCase.ChattingServerLoginRequest) {
      output.WriteRawTag(10);
      output.WriteMessage(ChattingServerLoginRequest);
    }
    if (chattingPayloadCase_ == ChattingPayloadOneofCase.ChattingServerLoginResponse) {
      output.WriteRawTag(18);
      output.WriteMessage(ChattingServerLoginResponse);
    }
    if (chattingPayloadCase_ == ChattingPayloadOneofCase.ChattingServerCreateRoomRequest) {
      output.WriteRawTag(26);
      output.WriteMessage(ChattingServerCreateRoomRequest);
    }
    if (chattingPayloadCase_ == ChattingPayloadOneofCase.ChattingServerCreateRoomResponse) {
      output.WriteRawTag(34);
      output.WriteMessage(ChattingServerCreateRoomResponse);
    }
    if (chattingPayloadCase_ == ChattingPayloadOneofCase.ChattingServerJoinRoomRequest) {
      output.WriteRawTag(42);
      output.WriteMessage(ChattingServerJoinRoomRequest);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (chattingPayloadCase_ == ChattingPayloadOneofCase.ChattingServerLoginRequest) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(ChattingServerLoginRequest);
    }
    if (chattingPayloadCase_ == ChattingPayloadOneofCase.ChattingServerLoginResponse) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(ChattingServerLoginResponse);
    }
    if (chattingPayloadCase_ == ChattingPayloadOneofCase.ChattingServerCreateRoomRequest) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(ChattingServerCreateRoomRequest);
    }
    if (chattingPayloadCase_ == ChattingPayloadOneofCase.ChattingServerCreateRoomResponse) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(ChattingServerCreateRoomResponse);
    }
    if (chattingPayloadCase_ == ChattingPayloadOneofCase.ChattingServerJoinRoomRequest) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(ChattingServerJoinRoomRequest);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(ChattingPacket other) {
    if (other == null) {
      return;
    }
    switch (other.ChattingPayloadCase) {
      case ChattingPayloadOneofCase.ChattingServerLoginRequest:
        if (ChattingServerLoginRequest == null) {
          ChattingServerLoginRequest = new global::C2SChattingServerLoginRequest();
        }
        ChattingServerLoginRequest.MergeFrom(other.ChattingServerLoginRequest);
        break;
      case ChattingPayloadOneofCase.ChattingServerLoginResponse:
        if (ChattingServerLoginResponse == null) {
          ChattingServerLoginResponse = new global::S2CChattingServerLoginResponse();
        }
        ChattingServerLoginResponse.MergeFrom(other.ChattingServerLoginResponse);
        break;
      case ChattingPayloadOneofCase.ChattingServerCreateRoomRequest:
        if (ChattingServerCreateRoomRequest == null) {
          ChattingServerCreateRoomRequest = new global::C2SChattingServerCreateRoomRequest();
        }
        ChattingServerCreateRoomRequest.MergeFrom(other.ChattingServerCreateRoomRequest);
        break;
      case ChattingPayloadOneofCase.ChattingServerCreateRoomResponse:
        if (ChattingServerCreateRoomResponse == null) {
          ChattingServerCreateRoomResponse = new global::S2CChattingServerCreateRoomResponse();
        }
        ChattingServerCreateRoomResponse.MergeFrom(other.ChattingServerCreateRoomResponse);
        break;
      case ChattingPayloadOneofCase.ChattingServerJoinRoomRequest:
        if (ChattingServerJoinRoomRequest == null) {
          ChattingServerJoinRoomRequest = new global::C2SChattingServerJoinRoomRequest();
        }
        ChattingServerJoinRoomRequest.MergeFrom(other.ChattingServerJoinRoomRequest);
        break;
    }

    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          global::C2SChattingServerLoginRequest subBuilder = new global::C2SChattingServerLoginRequest();
          if (chattingPayloadCase_ == ChattingPayloadOneofCase.ChattingServerLoginRequest) {
            subBuilder.MergeFrom(ChattingServerLoginRequest);
          }
          input.ReadMessage(subBuilder);
          ChattingServerLoginRequest = subBuilder;
          break;
        }
        case 18: {
          global::S2CChattingServerLoginResponse subBuilder = new global::S2CChattingServerLoginResponse();
          if (chattingPayloadCase_ == ChattingPayloadOneofCase.ChattingServerLoginResponse) {
            subBuilder.MergeFrom(ChattingServerLoginResponse);
          }
          input.ReadMessage(subBuilder);
          ChattingServerLoginResponse = subBuilder;
          break;
        }
        case 26: {
          global::C2SChattingServerCreateRoomRequest subBuilder = new global::C2SChattingServerCreateRoomRequest();
          if (chattingPayloadCase_ == ChattingPayloadOneofCase.ChattingServerCreateRoomRequest) {
            subBuilder.MergeFrom(ChattingServerCreateRoomRequest);
          }
          input.ReadMessage(subBuilder);
          ChattingServerCreateRoomRequest = subBuilder;
          break;
        }
        case 34: {
          global::S2CChattingServerCreateRoomResponse subBuilder = new global::S2CChattingServerCreateRoomResponse();
          if (chattingPayloadCase_ == ChattingPayloadOneofCase.ChattingServerCreateRoomResponse) {
            subBuilder.MergeFrom(ChattingServerCreateRoomResponse);
          }
          input.ReadMessage(subBuilder);
          ChattingServerCreateRoomResponse = subBuilder;
          break;
        }
        case 42: {
          global::C2SChattingServerJoinRoomRequest subBuilder = new global::C2SChattingServerJoinRoomRequest();
          if (chattingPayloadCase_ == ChattingPayloadOneofCase.ChattingServerJoinRoomRequest) {
            subBuilder.MergeFrom(ChattingServerJoinRoomRequest);
          }
          input.ReadMessage(subBuilder);
          ChattingServerJoinRoomRequest = subBuilder;
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
